package com.pl.maciej.services;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import com.pl.maciej.prog.Osoba;

public class OsobaDBManager {
	
	private Connection polaczenie;
	private Statement polecenie;
	private PreparedStatement polecenieDodaniaOsoby;
	private PreparedStatement polecenieOdczytuOsob;
	
	
	public OsobaDBManager()
	{
		try {
			Properties wlasciwosci = new Properties();
			
			try {
				wlasciwosci.load(ClassLoader.getSystemResourceAsStream("com/pl/maciej/jdbc.properties"));
			}
			catch (IOException e) {
				e.printStackTrace();
			}
			
			polaczenie = DriverManager.getConnection(wlasciwosci.getProperty("url"));
					
			polecenie = polaczenie.createStatement();
			boolean tablicaOsobIstnieje = false;
			
			ResultSet rs = polaczenie.getMetaData().getTables(null, null, null, null);
			
			while(rs.next() && !tablicaOsobIstnieje) {
				if("osoba".equalsIgnoreCase(rs.getString("TABLE_NAME")))
					tablicaOsobIstnieje = true;
			}
						
			if(!tablicaOsobIstnieje)
			{
				polecenie.executeUpdate("" +
					"CREATE TABLE osoba(" +
					"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
					"imie varchar(20)," +
					"nazwisko varchar(20)," +
					"" +
					")");
			}
			
			polecenieDodaniaOsoby = polaczenie.prepareStatement("" +
					"INSERT INTO osoba (imie, nazwisko) VALUES (?, ?)" +
					"");
			
			polecenieOdczytuOsob = polaczenie.prepareStatement("" +
					"SELECT * FROM osoba" +
					"");
			
		}
		catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	public void dodajOsobe(Osoba o) {
		try {
			polecenieDodaniaOsoby.setString(1, o.dajImie());
			polecenieDodaniaOsoby.setString(2, o.dajNazwisko());
			polecenieDodaniaOsoby.executeUpdate();
		} 
		catch (SQLException e) {
			e.printStackTrace();
		}
	
	}
	
	public List<Osoba> dajWszystkieOsoby() {
		
		List<Osoba> listaOsob = new ArrayList<Osoba>();
		try {
			ResultSet rs = polecenieOdczytuOsob.executeQuery();
			while(rs.next()) {
				listaOsob.add(new Osoba(rs.getString("imie"), rs.getString("nazwisko"), null));
			}
		}
		catch (SQLException e) {
			e.printStackTrace();
		}
		return listaOsob;
		
	}

}
